long_terms = ('XviD-ARROW',
               'AC3-LUSi',
               'AC3-FLAWL3SS',
               'AC3-ViSiON',
               'RoSubbed-playOFF',
               'D-Z0N3',
               'BDRip',
               'WEB-DL',
               'WEB.DL',
               'XviD-NYDIC',
               'x264-VoXHD',
               'H264-3Li',
               'XVID-WBZ',
               'DTS-WiKi',
               'PS3-TEAM',
               '2CH-aXXo',
               'iNTERNAL-FFM',
               '[Extended.Edition]',
               '[Eng]'
               )

short_terms = ('DTS',
                'Blu-ray',
                'QEBS',
                'PS3'
                )

famous_uploaders = ('LEGi0N',
                    'LUSi',
                    'TiMPE',
                    'FLAWL3SS',
                    'ViSiON',
                    'NYDIC',
                    'LTRG',
                    'ZMG',
                    'D-Z0N3',
                    'Hive-CM8',
                    'SCHIZO',
                    'NPW',
                    'Feel-Free',
                    'SHiRK',
                    'QUiET',
                    'GokU61',
                    'MANiAC',
                    '[Torrent-Force]',
                    'CROSSBOW',
                    'REFiNED',
                    'PRoDJi',
                    'SiNNERS',
                    'ViSTA',
                    'FraMeSToR',
                    'CtrlHD',
                    'REPACK-FASM',
                    'Vrxuniique',
                    'EuReKA',
                    'aXXo',
                    'DiCE',
                    'ESiR'
                    )

terms = long_terms + short_terms + famous_uploaders