long_tokens = ['XviD-ARROW',
               'AC3-LUSi',
               'AC3-FLAWL3SS',
               'AC3-ViSiON',
               'RoSubbed-playOFF',
               'D-Z0N3',
               'BDRip',
               'WEB-DL',
               'WEB.DL',
               'XviD-NYDIC',
               'x264-VoXHD',
               'H264-3Li',
               'XVID-WBZ',
               'DTS-WiKi',
               'PS3-TEAM'
               ]

short_tokens = ['DTS',
                'Blu-ray',
                'QEBS',
                'PS3']

famous_uploaders = ['LEGi0N',
                    'LUSi',
                    'TiMPE',
                    'FLAWL3SS',
                    'ViSiON',
                    'NYDIC',
                    'LTRG',
                    'ZMG',
                    'D-Z0N3',
                    'Hive-CM8',
                    'NPW',
                    'Feel-Free',
                    'SHiRK',
                    'QUiET',
                    'GokU61',
                    'MANiAC',
                    '[Torrent-Force]',
                    'CROSSBOW',
                    'REFiNED',
                    'PRoDJi',
                    'ViSTA',
                    'FraMeSToR',
                    'CtrlHD',
                    'REPACK-FASM',
                    'Vrxuniique',
                    'EuReKA'
                    ]

tokens = long_tokens + short_tokens + famous_uploaders